baseURL = "https://2019.djangocon.eu/"
languageCode = "en-us"
title = "DjangoCon Europe 2019"
theme = "dceu2019"
author = "Django Denmark"
sectionPagesMenu = "main"


[params]
    description = "DjangoCon Europe, In Copenhagen April 10-12th 2019"
    twittercardimage="twitter_card.png"
    headerimage = "logo.svg"
